# Configuração do banco H2
spring.datasource.url=jdbc:h2:mem:hackathon2026
spring.datasource.username=include
spring.datasource.password=hackathoninclude2026
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Regras para ler o data.sql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.encoding=UTF-8