-- Criação da tabela de Movimentações
CREATE TABLE IF NOT EXISTS movimentacao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    descricao VARCHAR(255) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    categoria VARCHAR(50) NOT NULL,
    valor DECIMAL(10,2) NOT NULL
);

-- Inserção de Entradas (Receitas)
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Projeto Site Institucional Clínica', 'ENTRADA', 'PROJETOS', 4500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Gestão Imobiliária', 'ENTRADA', 'PROJETOS', 8200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção E-commerce', 'ENTRADA', 'MANUTENCAO', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em UI/UX', 'ENTRADA', 'CONSULTORIA', 2500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aplicativo Delivery', 'ENTRADA', 'PROJETOS', 9800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Mensal - Cliente X', 'ENTRADA', 'MANUTENCAO', 800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Landing Page Evento', 'ENTRADA', 'PROJETOS', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria de Arquitetura AWS', 'ENTRADA', 'CONSULTORIA', 3000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Agendamento para Clínica', 'ENTRADA', 'PROJETOS', 6500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Automação de QA', 'ENTRADA', 'CONSULTORIA', 3200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de E-commerce Mês 01', 'ENTRADA', 'MANUTENCAO', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Dashboard de Dados para Startup', 'ENTRADA', 'PROJETOS', 5400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Site Institucional para Laboratório', 'ENTRADA', 'PROJETOS', 3800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Arquitetura Frontend', 'ENTRADA', 'CONSULTORIA', 2100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de App Mobile', 'ENTRADA', 'MANUTENCAO', 1800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('API de Integração de Pagamentos', 'ENTRADA', 'PROJETOS', 4900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Auditoria de Código e Testes API', 'ENTRADA', 'CONSULTORIA', 2700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Portal de Notícias Local', 'ENTRADA', 'PROJETOS', 4200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Sistema Legado Mês 02', 'ENTRADA', 'MANUTENCAO', 2000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Migração de Banco de Dados', 'ENTRADA', 'PROJETOS', 3500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Segurança de Logs', 'ENTRADA', 'CONSULTORIA', 4100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Landing Page para Evento Universitário', 'ENTRADA', 'PROJETOS', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Suporte Técnico Mensal Cliente Y', 'ENTRADA', 'MANUTENCAO', 950.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Gestão de Estoque', 'ENTRADA', 'PROJETOS', 8800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento de Equipe Externa (React)', 'ENTRADA', 'CONSULTORIA', 3000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Refatoração de Interface UI/UX', 'ENTRADA', 'PROJETOS', 4500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Preventiva de Servidores', 'ENTRADA', 'MANUTENCAO', 1300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('App de Controle de Frotas', 'ENTRADA', 'PROJETOS', 9200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Modelagem de Dados', 'ENTRADA', 'CONSULTORIA', 2800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Otimização de SEO e Performance', 'ENTRADA', 'PROJETOS', 2200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Atualização de Versão de Framework', 'ENTRADA', 'MANUTENCAO', 1600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plataforma EAD Customizada', 'ENTRADA', 'PROJETOS', 11500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Análise de Vulnerabilidades Web', 'ENTRADA', 'CONSULTORIA', 4500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Bot para Atendimento no WhatsApp', 'ENTRADA', 'PROJETOS', 3400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de E-commerce Mês 02', 'ENTRADA', 'MANUTENCAO', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Reservas para Hotel', 'ENTRADA', 'PROJETOS', 7600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mentoria Técnica para Devs Inciantes', 'ENTRADA', 'CONSULTORIA', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Integração com API dos Correios', 'ENTRADA', 'PROJETOS', 2900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Correção de Bugs Críticos (SLA)', 'ENTRADA', 'MANUTENCAO', 1100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aplicativo de Fidelidade', 'ENTRADA', 'PROJETOS', 8100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Infraestrutura Cloud', 'ENTRADA', 'CONSULTORIA', 3900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Dashboard de BI para Vendas', 'ENTRADA', 'PROJETOS', 6200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Site Corporativo', 'ENTRADA', 'MANUTENCAO', 850.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Desenvolvimento de MVP para Startup', 'ENTRADA', 'PROJETOS', 12000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Auditoria de Acessibilidade Web', 'ENTRADA', 'CONSULTORIA', 2300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plugin Customizado para WordPress', 'ENTRADA', 'PROJETOS', 1900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de Sistema RH Mês 01', 'ENTRADA', 'MANUTENCAO', 2500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Redesign de Portal de Ensino', 'ENTRADA', 'PROJETOS', 5100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Versionamento (Git)', 'ENTRADA', 'CONSULTORIA', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Criação de Identidade Visual e UI', 'ENTRADA', 'PROJETOS', 3600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajustes de Layout Responsivo', 'ENTRADA', 'MANUTENCAO', 700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Rastreamento de Entregas', 'ENTRADA', 'PROJETOS', 8900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mapeamento de Processos de Software', 'ENTRADA', 'CONSULTORIA', 2600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Desenvolvimento de Script de Automação', 'ENTRADA', 'PROJETOS', 1400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de Sistema RH Mês 02', 'ENTRADA', 'MANUTENCAO', 2500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plataforma de Votação Online', 'ENTRADA', 'PROJETOS', 5800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria de Escalabilidade de Banco', 'ENTRADA', 'CONSULTORIA', 4400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Portal do Aluno (Frontend)', 'ENTRADA', 'PROJETOS', 6700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Desenvolvimento de Chatbot para Telegram', 'ENTRADA', 'PROJETOS', 4500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Cultura DevOps', 'ENTRADA', 'CONSULTORIA', 3800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Portal de Notícias', 'ENTRADA', 'MANUTENCAO', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Gestão de Clínicas Veterinárias', 'ENTRADA', 'PROJETOS', 9500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Estruturação de QA', 'ENTRADA', 'CONSULTORIA', 4200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Otimização de Banco de Dados MySQL', 'ENTRADA', 'MANUTENCAO', 1800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Criação de Blog Corporativo', 'ENTRADA', 'PROJETOS', 2500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mentoria em Desenvolvimento React', 'ENTRADA', 'CONSULTORIA', 1600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Evolutiva App Cliente Z', 'ENTRADA', 'MANUTENCAO', 2100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Dashboard de Logística', 'ENTRADA', 'PROJETOS', 6800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Auditoria de Código Legado', 'ENTRADA', 'CONSULTORIA', 3500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajuste de Responsividade Móbile', 'ENTRADA', 'MANUTENCAO', 900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Integração com API de NF-e', 'ENTRADA', 'PROJETOS', 3100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento de Automação de Testes', 'ENTRADA', 'CONSULTORIA', 2900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de Sistema de Matrículas', 'ENTRADA', 'MANUTENCAO', 2400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aplicativo de Gestão de Tarefas', 'ENTRADA', 'PROJETOS', 8400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em LGPD para Sistemas', 'ENTRADA', 'CONSULTORIA', 4100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Atualização de Plugins WordPress', 'ENTRADA', 'MANUTENCAO', 600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plataforma de Crowdfunding', 'ENTRADA', 'PROJETOS', 11000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Migração de Hospedagem Web', 'ENTRADA', 'MANUTENCAO', 1300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria de Acessibilidade Digital', 'ENTRADA', 'CONSULTORIA', 2200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Ponto Eletrônico', 'ENTRADA', 'PROJETOS', 7300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Integrações ERP', 'ENTRADA', 'MANUTENCAO', 1900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Painel Administrativo Vendas', 'ENTRADA', 'PROJETOS', 5600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em CI/CD', 'ENTRADA', 'CONSULTORIA', 3700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Correção de Falhas de Segurança', 'ENTRADA', 'MANUTENCAO', 1450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Marketplace de Serviços Locais', 'ENTRADA', 'PROJETOS', 14500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Estruturação de Data Lake', 'ENTRADA', 'CONSULTORIA', 6000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de E-commerce Mês 03', 'ENTRADA', 'MANUTENCAO', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('API para Sincronização de Estoque', 'ENTRADA', 'PROJETOS', 4800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento em Testes Manuais', 'ENTRADA', 'CONSULTORIA', 1800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajuste em Rotas de Backend', 'ENTRADA', 'MANUTENCAO', 850.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Landing Page de Lançamento de Produto', 'ENTRADA', 'PROJETOS', 1700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria de Performance Web', 'ENTRADA', 'CONSULTORIA', 2600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Limpeza e Otimização de Servidor', 'ENTRADA', 'MANUTENCAO', 1100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema CRM Customizado', 'ENTRADA', 'PROJETOS', 10500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mapeamento de Requisitos App Mobile', 'ENTRADA', 'CONSULTORIA', 3100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Suporte Técnico Mensal Cliente W', 'ENTRADA', 'MANUTENCAO', 950.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Portal de Transparência Municipal', 'ENTRADA', 'PROJETOS', 8900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Nuvem Azure', 'ENTRADA', 'CONSULTORIA', 4300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajustes de SEO On-page', 'ENTRADA', 'MANUTENCAO', 750.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aplicativo de Guia Turístico', 'ENTRADA', 'PROJETOS', 6400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mentoria em Clean Architecture', 'ENTRADA', 'CONSULTORIA', 2000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de Portal Mês 01', 'ENTRADA', 'MANUTENCAO', 1250.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Vendas PDV', 'ENTRADA', 'PROJETOS', 7800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Análise de Dados e BI Cliente X', 'ENTRADA', 'CONSULTORIA', 5200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Redesign de E-mail Marketing', 'ENTRADA', 'MANUTENCAO', 600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plataforma de Assinaturas de Conteúdo', 'ENTRADA', 'PROJETOS', 12000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop de Metodologias Ágeis In Company', 'ENTRADA', 'CONSULTORIA', 3500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Corretiva Banco de Dados', 'ENTRADA', 'MANUTENCAO', 1400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Desenvolvimento de Dashboard com React e Tailwind', 'ENTRADA', 'PROJETOS', 5800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria de Testes E2E com Cypress', 'ENTRADA', 'CONSULTORIA', 3400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Automação de Validação de APIs (Postman)', 'ENTRADA', 'PROJETOS', 4100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Projeto de Extensão para o IMD', 'ENTRADA', 'PROJETOS', 2500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Portal Institucional da UFRN', 'ENTRADA', 'MANUTENCAO', 1800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Implantação de Cultura de QA e Bug Tracking', 'ENTRADA', 'CONSULTORIA', 4500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Refatoração de Frontend Legado para React', 'ENTRADA', 'PROJETOS', 7200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mentoria sobre Ciclo de Vida de Bugs (Jira)', 'ENTRADA', 'CONSULTORIA', 1500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Gestão de Notas Acadêmicas', 'ENTRADA', 'PROJETOS', 6100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Testes de Carga e Performance', 'ENTRADA', 'MANUTENCAO', 2200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Criação de Biblioteca de Componentes UI', 'ENTRADA', 'PROJETOS', 3900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Arquitetura de Software', 'ENTRADA', 'CONSULTORIA', 5000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajuste de Layouts Flexbox/Grid', 'ENTRADA', 'MANUTENCAO', 850.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('App de Mapeamento de Salas', 'ENTRADA', 'PROJETOS', 4600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Revisão de Código e Boas Práticas', 'ENTRADA', 'CONSULTORIA', 2800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Integração de Gateway de Pagamento', 'ENTRADA', 'PROJETOS', 3300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de App de Mobilidade Mês 01', 'ENTRADA', 'MANUTENCAO', 2000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Chamados para TI Local', 'ENTRADA', 'PROJETOS', 5500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Segurança de Redes', 'ENTRADA', 'CONSULTORIA', 3700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Evolutiva de API REST', 'ENTRADA', 'MANUTENCAO', 1400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plataforma de Cursos Livres', 'ENTRADA', 'PROJETOS', 9200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Análise de Dados do Censo Estudantil', 'ENTRADA', 'CONSULTORIA', 4800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Criação de Scripts de Web Scraping', 'ENTRADA', 'PROJETOS', 2600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Migração de Servidores Locais para Nuvem', 'ENTRADA', 'MANUTENCAO', 3100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aplicativo de Gestão Financeira Pessoal', 'ENTRADA', 'PROJETOS', 8100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop Prático de Testes Manuais', 'ENTRADA', 'CONSULTORIA', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajustes de Acessibilidade (WCAG)', 'ENTRADA', 'MANUTENCAO', 950.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema de Controle de Ponto Digital', 'ENTRADA', 'PROJETOS', 5400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Banco de Dados NoSQL', 'ENTRADA', 'CONSULTORIA', 2900.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sustentação de Sistema Clínico Mês 05', 'ENTRADA', 'MANUTENCAO', 1600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('E-commerce de Roupas Sustentáveis', 'ENTRADA', 'PROJETOS', 10500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Auditoria de UX/UI em Plataforma', 'ENTRADA', 'CONSULTORIA', 2100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Bot de Discord Institucional', 'ENTRADA', 'PROJETOS', 1800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Limpeza de Dados e ETL', 'ENTRADA', 'MANUTENCAO', 1300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Sistema ERP para Pequeno Varejo', 'ENTRADA', 'PROJETOS', 14000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Consultoria em Metodologia Kanban', 'ENTRADA', 'CONSULTORIA', 1750.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Atualização de Dependências NPM', 'ENTRADA', 'MANUTENCAO', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('App de Receitas Locais', 'ENTRADA', 'PROJETOS', 4200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mentoria em Engenharia de Software', 'ENTRADA', 'CONSULTORIA', 3000.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Suporte Nível 3 Sistema X', 'ENTRADA', 'MANUTENCAO', 2200.00);


-- Inserção de Saídas (Despesas)
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença Zoom Mensal', 'SAIDA', 'FERRAMENTAS', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso de Spring Boot Avançado', 'SAIDA', 'CAPACITACAO', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto DAS', 'SAIDA', 'IMPOSTOS', 280.50);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Monitor Dell', 'SAIDA', 'PATRIMONIO', 1450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Hospedagem AWS (Mês atual)', 'SAIDA', 'FERRAMENTAS', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto ISS', 'SAIDA', 'IMPOSTOS', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Certificação AWS Cloud Practitioner', 'SAIDA', 'CAPACITACAO', 500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Cadeira Ergonômica', 'SAIDA', 'PATRIMONIO', 980.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença Figma Mensal', 'SAIDA', 'FERRAMENTAS', 85.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop de Metodologias Ágeis', 'SAIDA', 'CAPACITACAO', 200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Contabilidade', 'SAIDA', 'HONORARIOS', 300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Upgrade de Memória RAM', 'SAIDA', 'PATRIMONIO', 250.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Vercel Pro', 'SAIDA', 'FERRAMENTAS', 110.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto Simples Nacional', 'SAIDA', 'IMPOSTOS', 450.75);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Teclado Mecânico', 'SAIDA', 'PATRIMONIO', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso de Cypress na Udemy', 'SAIDA', 'CAPACITACAO', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença do Postman Pro', 'SAIDA', 'FERRAMENTAS', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 01', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Monitor Secundário', 'SAIDA', 'PATRIMONIO', 850.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Emissão de Nota Fiscal', 'SAIDA', 'IMPOSTOS', 45.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura GitHub Copilot', 'SAIDA', 'FERRAMENTAS', 95.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop de Qualidade de Software', 'SAIDA', 'CAPACITACAO', 250.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Jurídicos (Contratos)', 'SAIDA', 'HONORARIOS', 800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de SSD NVMe 1TB', 'SAIDA', 'PATRIMONIO', 420.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto de Renda PJ', 'SAIDA', 'IMPOSTOS', 520.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Hospedagem de Site Institucional', 'SAIDA', 'FERRAMENTAS', 60.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Livro de Estrutura de Dados', 'SAIDA', 'CAPACITACAO', 85.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Ar Condicionado (Sede)', 'SAIDA', 'PATRIMONIO', 200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Canva Pro Mensal', 'SAIDA', 'FERRAMENTAS', 35.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto IOF', 'SAIDA', 'IMPOSTOS', 25.50);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Mouse Ergonômico', 'SAIDA', 'PATRIMONIO', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Certificação de Scrum Master', 'SAIDA', 'CAPACITACAO', 750.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 02', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença Google Workspace', 'SAIDA', 'FERRAMENTAS', 220.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto PIS/COFINS', 'SAIDA', 'IMPOSTOS', 310.20);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Quadro Branco', 'SAIDA', 'PATRIMONIO', 280.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso de Tailwind CSS Avançado', 'SAIDA', 'CAPACITACAO', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Jira Software', 'SAIDA', 'FERRAMENTAS', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Material de Escritório (Papelaria)', 'SAIDA', 'PATRIMONIO', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa Bancária de Manutenção', 'SAIDA', 'HONORARIOS', 55.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto Municipal Suplementar', 'SAIDA', 'IMPOSTOS', 80.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Webcam Full HD', 'SAIDA', 'PATRIMONIO', 310.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Inscrição em Conferência Tech', 'SAIDA', 'CAPACITACAO', 400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Notion Team', 'SAIDA', 'FERRAMENTAS', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 03', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Recarga de Cartuchos/Toner', 'SAIDA', 'PATRIMONIO', 90.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto Retido na Fonte (IRRF)', 'SAIDA', 'IMPOSTOS', 145.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Domínio Web Anual (.com.br)', 'SAIDA', 'FERRAMENTAS', 40.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento Interno de Git', 'SAIDA', 'CAPACITACAO', 100.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Roteador Wi-Fi 6', 'SAIDA', 'PATRIMONIO', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Registro em Cartório', 'SAIDA', 'HONORARIOS', 115.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Serviço de Nuvem (Database AWS)', 'SAIDA', 'FERRAMENTAS', 320.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Guia de Arrecadação Estadual', 'SAIDA', 'IMPOSTOS', 190.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Livro de Clean Code', 'SAIDA', 'CAPACITACAO', 110.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Nobreak', 'SAIDA', 'PATRIMONIO', 550.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Consultoria Financeira', 'SAIDA', 'HONORARIOS', 600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Slack Premium', 'SAIDA', 'FERRAMENTAS', 210.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Ajuste Fiscal (Multa Atraso)', 'SAIDA', 'IMPOSTOS', 35.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Participação em Hackathon Externo', 'SAIDA', 'CAPACITACAO', 200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Suporte para Notebook', 'SAIDA', 'PATRIMONIO', 85.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Certificado Digital e-CNPJ', 'SAIDA', 'HONORARIOS', 230.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plano de Internet Corporativo', 'SAIDA', 'FERRAMENTAS', 199.90);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura JetBrains All Products', 'SAIDA', 'FERRAMENTAS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto DAS Mês Atual', 'SAIDA', 'IMPOSTOS', 290.40);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Hub USB-C', 'SAIDA', 'PATRIMONIO', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Alura Empresas', 'SAIDA', 'CAPACITACAO', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Manutenção de Conta PJ', 'SAIDA', 'HONORARIOS', 65.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença Trello Premium', 'SAIDA', 'FERRAMENTAS', 145.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Pagamento de Guia ISS', 'SAIDA', 'IMPOSTOS', 185.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Cadeira de Escritório', 'SAIDA', 'PATRIMONIO', 750.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso de Spring Security', 'SAIDA', 'CAPACITACAO', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 04', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Hospedagem DigitalOcean Mensal', 'SAIDA', 'FERRAMENTAS', 210.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto de Renda Retido na Fonte', 'SAIDA', 'IMPOSTOS', 130.50);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Reposição de Fones de Ouvido (Headset)', 'SAIDA', 'PATRIMONIO', 240.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Inscrição em Simpósio de Tecnologia', 'SAIDA', 'CAPACITACAO', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assessoria Jurídica Mês 01', 'SAIDA', 'HONORARIOS', 500.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Figma Organization', 'SAIDA', 'FERRAMENTAS', 160.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa Alvará de Funcionamento', 'SAIDA', 'IMPOSTOS', 320.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Adaptadores HDMI', 'SAIDA', 'PATRIMONIO', 80.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Livro sobre Arquitetura de Software', 'SAIDA', 'CAPACITACAO', 135.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Transferência PIX PJ', 'SAIDA', 'HONORARIOS', 15.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Créditos API ChatGPT/OpenAI', 'SAIDA', 'FERRAMENTAS', 115.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Guia Sindical Anual', 'SAIDA', 'IMPOSTOS', 140.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Impressora', 'SAIDA', 'PATRIMONIO', 110.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento de Liderança', 'SAIDA', 'CAPACITACAO', 550.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 05', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença SonarQube Anual', 'SAIDA', 'FERRAMENTAS', 800.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Pagamento CSLL', 'SAIDA', 'IMPOSTOS', 210.30);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Estabilizador de Energia', 'SAIDA', 'PATRIMONIO', 190.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Certificação em DevOps', 'SAIDA', 'CAPACITACAO', 620.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Serviço de Despachante', 'SAIDA', 'HONORARIOS', 250.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Miro Mensal', 'SAIDA', 'FERRAMENTAS', 75.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto IRPJ Trimestral', 'SAIDA', 'IMPOSTOS', 480.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Aquisição de Webcams Extras', 'SAIDA', 'PATRIMONIO', 300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso Prático de Docker', 'SAIDA', 'CAPACITACAO', 95.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Custas de Cartório (Reconhecimento de Firma)', 'SAIDA', 'HONORARIOS', 45.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Plano de Dados Mobile Corporativo', 'SAIDA', 'FERRAMENTAS', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Licenciamento de Software Municipal', 'SAIDA', 'IMPOSTOS', 90.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Mesa Digitalizadora', 'SAIDA', 'PATRIMONIO', 410.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop de Comunicação Assertiva', 'SAIDA', 'CAPACITACAO', 220.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 06', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mensalidade Banco de Imagens (Freepik)', 'SAIDA', 'FERRAMENTAS', 55.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Multa por Atraso de Declaração', 'SAIDA', 'IMPOSTOS', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Troca de Bateria de Notebook', 'SAIDA', 'PATRIMONIO', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Revista de Tecnologia', 'SAIDA', 'CAPACITACAO', 45.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assessoria de Imprensa Mês 01', 'SAIDA', 'HONORARIOS', 700.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Serviço de E-mail Marketing (Mailchimp)', 'SAIDA', 'FERRAMENTAS', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Diferencial de Alíquota (DIFAL)', 'SAIDA', 'IMPOSTOS', 75.80);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Apoio para Pés', 'SAIDA', 'PATRIMONIO', 90.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Participação em Feira de Empreendedorismo', 'SAIDA', 'CAPACITACAO', 300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Renovação de Certificado Digital', 'SAIDA', 'HONORARIOS', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Inscrição Curso Especialista React', 'SAIDA', 'CAPACITACAO', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Licença PyCharm Professional', 'SAIDA', 'FERRAMENTAS', 320.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mensalidade Plano Vercel Enterprise', 'SAIDA', 'FERRAMENTAS', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Guia de Recolhimento da União (GRU)', 'SAIDA', 'IMPOSTOS', 85.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção Preventiva dos Computadores', 'SAIDA', 'PATRIMONIO', 400.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Cypress Cloud Mensal', 'SAIDA', 'FERRAMENTAS', 210.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 07', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto sobre Serviços (ISS) Natal', 'SAIDA', 'IMPOSTOS', 270.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Placa Mãe MSI A520M Pro', 'SAIDA', 'PATRIMONIO', 450.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Processador AMD Ryzen 5', 'SAIDA', 'PATRIMONIO', 850.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Treinamento em Qualidade de Software (QA)', 'SAIDA', 'CAPACITACAO', 300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mensalidade AWS Relational Database', 'SAIDA', 'FERRAMENTAS', 125.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Registro INPI', 'SAIDA', 'HONORARIOS', 145.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Diferença de ICMS Mês Passado', 'SAIDA', 'IMPOSTOS', 92.50);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Pasta Térmica e Cabos', 'SAIDA', 'PATRIMONIO', 65.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso Completo de Tailwind CSS', 'SAIDA', 'CAPACITACAO', 120.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 08', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura Serviço de VPN', 'SAIDA', 'FERRAMENTAS', 45.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Contribuição Previdenciária Patronal', 'SAIDA', 'IMPOSTOS', 315.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de HD Externo de Backup', 'SAIDA', 'PATRIMONIO', 280.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Inscrição em Evento de Tecnologia em Natal', 'SAIDA', 'CAPACITACAO', 180.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Mensalidade Plataforma de UX (Hotjar)', 'SAIDA', 'FERRAMENTAS', 90.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Auditoria Contábil Anual', 'SAIDA', 'HONORARIOS', 1200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('DARF Mensal Referência', 'SAIDA', 'IMPOSTOS', 410.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Substituição de Roteador do Escritório', 'SAIDA', 'PATRIMONIO', 150.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Livro sobre Blockchain e Segurança', 'SAIDA', 'CAPACITACAO', 110.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 09', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura de Ferramenta de BI', 'SAIDA', 'FERRAMENTAS', 300.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Retenção de Tributos Federais', 'SAIDA', 'IMPOSTOS', 255.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Limpeza Profissional do Servidor', 'SAIDA', 'PATRIMONIO', 200.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Workshop de Inteligência Emocional', 'SAIDA', 'CAPACITACAO', 250.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Licença Anual Antivírus Corporativo', 'SAIDA', 'FERRAMENTAS', 420.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Taxa de Reativação de Domínio', 'SAIDA', 'HONORARIOS', 80.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Imposto de Exportação de Serviço', 'SAIDA', 'IMPOSTOS', 140.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Compra de Cadeiras para Reunião', 'SAIDA', 'PATRIMONIO', 600.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Curso de Gestão de Projetos Ágeis', 'SAIDA', 'CAPACITACAO', 190.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Honorários Contábeis Mês 10', 'SAIDA', 'HONORARIOS', 350.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Assinatura de Banco de Dados na Nuvem', 'SAIDA', 'FERRAMENTAS', 260.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Recolhimento FGTS Funcionários', 'SAIDA', 'IMPOSTOS', 530.00);
INSERT INTO movimentacao (descricao, tipo, categoria, valor) VALUES ('Manutenção de Câmeras de Segurança', 'SAIDA', 'PATRIMONIO', 180.00);