CREATE TABLE IF NOT EXISTS avaliacao (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nome_cliente VARCHAR(100) NOT NULL,
    nome_projeto VARCHAR(100) NOT NULL,
    nota INT NOT NULL,
    comentario TEXT
);

-- Inserções 1-100
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Restaurante Sabor Potiguar', 'Aplicativo Delivery', 5, 'Excelente entrega, o app não trava!');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Vida', 'Sistema de Agendamento', 2, 'Muito atraso na entrega e o sistema tem bugs.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Startup Inova', 'Dashboard de Vendas', 4, 'Bom trabalho. Faltou refinamento no layout.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Laboratório IMD', 'Portal Acadêmico', 5, 'Perfeito! Rápido e busca textual excelente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Escola Aprender', 'Plataforma EAD', 1, 'Péssimo. Sistema cai o tempo todo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Empresa X', 'Site Institucional', 3, 'Site bonito, mas demorou muito para responder.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Centro', 'E-commerce', 5, 'Integração com pagamento excelente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Consultoria Ágil', 'App de Gestão', 4, 'Gostei, login poderia ser mais rápido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Varejo Natal', 'Sistema de Estoque', 2, 'Perda de dados no primeiro mês. Ruim.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Tech Soluções', 'API de Integração', 5, 'Código limpo e bem documentado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Padaria Boa Viagem', 'App de Fidelidade', 4, 'Clientes gostando, mas tela inicial é básica.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Academia Força', 'Controle de Catraca', 1, 'Não integra direito com o backend.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Imobiliária Lar', 'Portal de Imóveis', 5, 'Ficou maravilhoso. Filtro muito rápido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Escritório Advocacia', 'Gestão de Processos', 3, 'Atende ao básico, mas prometeu mais.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Sorriso', 'Odonto Web', 5, 'Equipe atenciosa e pontual.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Petshop Animalia', 'Agendamento Banho', 2, 'Interface confusa para os usuários.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina CarroZero', 'Controle de OS', 4, 'Sistema robusto, detalhes de interface.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Supermercado Preço Bom', 'App de Ofertas', 1, 'Muitos bugs. App fecha sozinho.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Transportadora Log', 'Rastreio Web', 5, 'Funciona perfeitamente. Reduziu suporte.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Salão Beleza', 'Agenda App', 3, 'Mediano. Cor não combinou com marca.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Restaurante Mar', 'Cardápio Digital', 5, 'Rápido e responsivo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Visão', 'Prontuário', 2, 'Dificuldade de exportar em PDF.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('EducaTech', 'Plataforma Provas', 4, 'Muito bom. Alguma lentidão.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Projeto UFRN', 'Banco Dados Web', 5, 'Excelente estrutura de dados.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Pizzaria Forno', 'App Delivery', 1, 'Pedidos sumindo do sistema. Ruim.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Coworking Natal', 'Reserva de Salas', 5, 'Integração Google Calendar top.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Marketing', 'Dashboard Analytics', 4, 'Bom design, mas gráficos lentos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Farmácia Saúde', 'E-commerce', 3, 'Layout bonito, integração falha.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Construtora Edifica', 'Portal Cliente', 5, 'Excelente trabalho da equipe.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('ONG Ajuda', 'Site Doações', 5, 'Maravilhoso. Ajudou arrecadação.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Barbearia Estilo', 'App Agendamento', 2, 'App pesado e consome muita bateria.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Livraria Cultura', 'Loja Virtual', 4, 'Ótima busca, carrinho com erro.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Sindicato X', 'Portal Notícias', 3, 'Painel admin complicado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Eventos RN', 'Venda Ingressos', 1, 'Sistema travou no dia do evento.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clube Vantagens', 'App Mobile', 5, 'Nenhum bug. Código sólido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Hotel Praia', 'Reserva Online', 4, 'Muito bom. Suporte ágil.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Pousada Sol', 'Site Institucional', 5, 'Lindo design e rápido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Boutique Moda', 'E-commerce', 2, 'Imagens distorcidas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Contabilidade Y', 'Sistema Interno', 3, 'Demorou além do prazo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estúdio Fotos', 'Portfólio Web', 5, 'Entregue antes do prazo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Suplementos', 'E-commerce', 4, 'Integração PIX ficou muito boa.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Colégio Novo', 'Diário Eletrônico', 1, 'Notas somem. Professores furiosos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Estética', 'Gestão Clientes', 5, 'Facilitou muito. Ótimo UX.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Hamburgueria', 'App Delivery', 4, 'Faltou editar pedido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Autopeças', 'Estoque', 2, 'Busca muito lenta.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Ótica Visão', 'Catálogo Online', 5, 'Elegante e funcional.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Papelaria', 'Loja Virtual', 3, 'Problemas com variações.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Lavanderia', 'App Coleta', 4, 'Faltou notificação push.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Dentista XYZ', 'Site', 5, 'Simples e direto.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Distribuidora', 'Portal B2B', 1, 'Sistema inacabado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Gráfica Express', 'Orçamentos', 5, 'Eficiente, reduziu tempo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Sorveteria Gelato', 'Fidelidade', 4, 'Faltou cor no app.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Seguradora X', 'Sinistros', 2, 'Interface nada amigável.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Imobiliária Y', 'CRM', 5, 'Gestão de leads excelente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Centro Médico', 'Chamadas', 3, 'Perde conexão.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Escola Inglês', 'Portal Aluno', 4, 'Falta fórum de dúvidas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Vet', 'Prontuário Pet', 5, 'Muito prático.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Empresa Limpeza', 'Escalas', 1, 'Horários trocados.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Consultoria Z', 'Site', 4, 'Entrega no prazo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Roupas', 'E-commerce', 2, 'Módulo de frete falha.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Viagens', 'Reservas', 5, 'API de hotéis top.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Hostel Juventude', 'Interno', 4, 'Bom para quartos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina Moto', 'Peças', 3, 'Básico.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Tech Start', 'Landing Page', 5, 'Conversão alta.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Sindicato Y', 'App Informativo', 2, 'Falhas no iOS.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cervejaria', 'E-commerce', 5, 'Admin é top.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Banda Local', 'Site', 5, 'Design arrojado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Editora', 'Catálogo Web', 4, 'Bem modelado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Eletro', 'Trocas', 1, 'Regra errada.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estúdio Dança', 'Turmas', 4, 'Falta WhatsApp.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Consultório Psi', 'Agendamento', 5, 'Privacidade respeitada.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Floricultura', 'Delivery', 3, 'Demora nas lojas app.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Marcenaria', 'Orçamentos', 5, 'PDF rápido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Vidraçaria', 'Site', 4, 'SEO ok.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Modelos', 'Portfólio', 2, 'Fotos perdem qualidade.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Transporte Escolar', 'Rotas', 1, 'GPS falha.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clube Assinatura', 'Recorrente', 5, 'Sem erros.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Provedor Internet', 'Área Cliente', 4, 'Bug mobile.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('ONG Animais', 'Adoção', 5, 'Filtros ótimos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fazenda', 'Gestão Agro', 3, 'Depende de internet.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fisioterapia', 'Evolução', 5, 'Acompanhamento diário.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estacionamento', 'Vagas', 2, 'Trava no rush.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cinema', 'Ingressos', 4, 'Mapa precisa melhorar.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Informática', 'E-commerce', 5, 'Vendas subiram.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Serralheria', 'Orçamento', 1, 'Cálculo errado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Bazar', 'Loja Virtual', 4, 'Fácil de usar.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Museu', 'Tour', 5, 'Imersivo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Natação', 'Mensalidades', 3, 'Email falha.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Açougue', 'Entregas', 5, 'Gestão perfeita.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Segurança', 'Câmeras', 2, 'Delay alto.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Esportiva', 'Treinos', 4, 'Falta cronômetro.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Tintas', 'Simulador', 5, 'Muito bem feito.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Repouso', 'Pacientes', 1, 'Confuso.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cooperativa', 'Cooperados', 4, 'Estável.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Grife', 'Vitrine', 5, 'Design premium.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estética', 'Agenda', 3, 'Várias correções.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Seminovos', 'Site', 5, 'Busca perfeita.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Caçambas', 'Locação', 2, 'Fluxo errado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Lava Jato', 'Agendamento', 4, 'Funcional.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Ateliê', 'Encomendas', 5, 'Acompanhamento ótimo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Padaria do Pão', 'Sistema de Pedidos', 5, 'Melhorou muito a agilidade da cozinha.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Consultório Odonto', 'Prontuário Digital', 2, 'O sistema trava ao anexar radiografias pesadas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Turismo', 'Booking Web', 4, 'Interface clara e objetiva.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Calçados', 'E-commerce', 5, 'Conversão de vendas aumentou bastante.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Academia Fitness', 'App de Treino', 1, 'Os treinos não sincronizam com o celular.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Restaurante Grill', 'Cardápio QR', 3, 'O design é ok, mas o carregamento é demorado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina Mecânica', 'Gestão de Clientes', 5, 'Muito bom para organizar a agenda.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Games', 'E-commerce', 4, 'Bom sistema, mas faltam filtros de categoria.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Barbearia Premium', 'Agenda App', 5, 'Fácil de usar e muito intuitivo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Escritório Contábil', 'Portal Financeiro', 2, 'Erros constantes no cálculo de impostos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Pizzaria Delivery', 'App de Vendas', 5, 'Excelente experiência de usuário.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Móveis', 'Catálogo Web', 4, 'Visual impecável, falta apenas zoom nas fotos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Colégio Bilíngue', 'Portal Escolar', 3, 'Funciona, mas a interface é muito antiga.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Psicológica', 'Agendamento Web', 5, 'Seguro e muito fácil para os pacientes.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Lavanderia Rápida', 'App de Coleta', 1, 'Cancelamento de pedidos não notifica o cliente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Sorveteria Artesanal', 'Fidelidade', 4, 'Ótimo incentivo para os clientes.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Boutique Feminina', 'Loja Virtual', 5, 'Muito elegante e converte bem.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina Elétrica', 'Controle de Serviços', 2, 'O sistema perde as notas salvas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência de Marketing', 'CRM de Projetos', 4, 'Gostamos da organização, falta apenas automação.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Brinquedos', 'E-commerce', 5, 'Perfeito. Nenhuma falha encontrada.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Centro Esportivo', 'Aluguel de Quadras', 3, 'Cumpriu o prometido, sem grandes diferenciais.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Distribuidora de Água', 'Pedidos App', 5, 'Agilizou nosso atendimento em 100%.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Dermato', 'Agenda', 4, 'Muito bom, agilidade no processo de marcação.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Hamburgueria Gourmet', 'Delivery', 1, 'Horrível, o site não abre no Chrome.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Tintas', 'Simulador', 5, 'O sistema é muito rápido e preciso.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência de Viagens', 'Booking', 4, 'Ótima usabilidade.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Serralheria Artística', 'Orçamentos', 5, 'Ajudou a profissionalizar nossa empresa.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Vidraçaria Especial', 'Site', 3, 'Bom, mas a versão mobile é lenta.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Informática', 'E-commerce', 5, 'Navegação incrível.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Transporte Escolar', 'App', 1, 'Localização totalmente imprecisa.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clube de Assinatura', 'Portal', 5, 'Gestão de usuários muito eficiente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Provedor Internet', 'Cliente', 4, 'Atende bem nossas necessidades.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('ONG Proteção', 'Adoção', 5, 'Muito bem estruturado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fazenda Local', 'Gestão', 3, 'Funciona melhor no desktop.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fisioterapia Clínica', 'Evolução', 5, 'Melhorou o registro dos prontuários.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estacionamento Central', 'Vagas', 2, 'Lentidão insuportável no horário de pico.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cinema Multiplex', 'Ingressos', 4, 'Ótimo sistema de vendas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Computadores', 'E-commerce', 5, 'Estável e muito rápido.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Serralheria', 'Orçamento', 1, 'Cálculo de preço todo errado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Bazar do Bairro', 'Loja Virtual', 4, 'Muito simples e eficaz.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Museu Histórico', 'Tour', 5, 'Design muito elegante.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Natação Kids', 'Pagamentos', 3, 'O sistema é complexo para o usuário final.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Açougue Premium', 'Entregas', 5, 'Logística muito bem organizada.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Empresa Segurança', 'Monitoramento', 2, 'Delay de sinal de vídeo é um problema.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Assessoria Esporte', 'Treinos', 4, 'Conteúdo de alta qualidade.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja de Tintas', 'Simulador', 5, 'Excelente ferramenta de vendas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Repouso Sênior', 'Pacientes', 1, 'Dificuldade de navegação extrema.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cooperativa Agrícola', 'Cooperados', 4, 'Bem integrado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Grife Luxo', 'Vitrine', 5, 'Visual de alta performance.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estética Avançada', 'Agenda', 3, 'Precisa de mais atualizações.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Revenda Seminovos', 'Site', 5, 'Filtros de busca muito eficientes.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Caçambas Locação', 'Controle', 2, 'Muitos bugs na atualização de status.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Lava Jato Rápido', 'Agenda', 4, 'Bom sistema, cumpre o papel.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Ateliê de Costura', 'Produção', 5, 'Organizou nossa linha de montagem.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Restaurante Sabor', 'Delivery', 5, 'Sucesso total entre os clientes.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Odonto', 'Prontuário', 2, 'Interface pouco intuitiva.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Turismo', 'Booking', 4, 'Melhorou nossa conversão.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Calçados', 'Ecommerce', 5, 'Sem reclamações.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Academia Fit', 'App', 1, 'Desinstalei de tão lento.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Grill Sabor', 'Cardápio', 3, 'Poderia ter mais fotos.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina Carros', 'Gestão', 5, 'Agenda muito prática.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Games Shop', 'Ecommerce', 4, 'Faltam opções de pagamento.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Barbearia Elite', 'App', 5, 'Super rápido e fácil.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Contabilidade Pro', 'Portal', 2, 'Erros em arquivos enviados.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Pizzaria Delivery', 'App', 5, 'Perfeito, agiliza muito.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Móveis Planejados', 'Catálogo', 4, 'Fotos excelentes.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Colégio', 'Portal', 3, 'Layout ultrapassado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Psico', 'Agendamento', 5, 'Muito seguro.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Lavanderia Express', 'App', 1, 'Não recebi notificação.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Sorveteria Gelato', 'Fidelidade', 4, 'Clientes amaram.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Boutique Feminina', 'Virtual', 5, 'Design incrível.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Oficina Elétrica', 'Serviços', 2, 'Perda de dados recorrente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Marketing CRM', 'Projetos', 4, 'Boa organização.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Brinquedos Shop', 'Ecommerce', 5, 'Sem falhas.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Centro Esporte', 'Quadras', 3, 'Sem diferenciais.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Água Distribuidora', 'Pedidos', 5, 'Agilidade máxima.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Clínica Dermato', 'Agenda', 4, 'Muito bom.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Hamburgueria', 'Delivery', 1, 'Não abre no navegador.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Simulador Tintas', 'Simulador', 5, 'Rápido e preciso.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Agência Viagem', 'Booking', 4, 'Boa usabilidade.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Serralheria Arte', 'Orçamentos', 5, 'Profissionalizou muito.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Vidraçaria', 'Site', 3, 'Versão mobile lenta.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Loja Infotech', 'Ecommerce', 5, 'Navegação top.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Escolar Transp', 'Rotas', 1, 'GPS falha muito.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Assinatura Clube', 'Portal', 5, 'Gestão eficiente.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Internet Prov', 'Cliente', 4, 'Atende bem.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('ONG Animais', 'Adoção', 5, 'Estrutura top.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fazenda Gestão', 'Agro', 3, 'Melhor desktop.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Fisio Clínica', 'Prontuário', 5, 'Registro perfeito.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Estacionamento', 'Vagas', 2, 'Trava no horário de pico.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Cinema Multiplex', 'Vendas', 4, 'Bom sistema.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Computadores', 'Ecommerce', 5, 'Estável.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Serralheria', 'Orçamento', 1, 'Cálculo errado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Bazar Local', 'Virtual', 4, 'Simples.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Museu Tour', 'Virtual', 5, 'Imersivo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Natação Kids', 'Pagos', 3, 'Complexo.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Açougue Delivery', 'App', 5, 'Organizado.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Segurança Cam', 'Monitor', 2, 'Delay alto.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('Esporte Assessoria', 'Treinos', 4, 'Alta qualidade.');
INSERT INTO avaliacao (nome_cliente, nome_projeto, nota, comentario) VALUES ('João Acessórios', 'App', 5, 'Alta qualidade e impulsionou minhas vendas.');